export const TAKE_SEAT_ACTION = "TAKE_SEAT_ACTION";
export const UPDATE_USER_FORM_ACTION = "UPDATE_USER_FORM_ACTION";
export const SUBMIT_USER_FORM_ACTION = "SUBMIT_USER_FORM_ACTION";
export const UPDATE_SITSIT_FORM_ACTION = "UPDATE_SITSIT_FORM_ACTION";
export const SUBMIT_SITSIT_FORM_ACTION = "SUBMIT_SITSIT_FORM_ACTION";
